name: Build and Push Docker server image

on:
  push:
    branches: master
    paths:
    - '**Dockerfile'
    - '**docker.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'change tag name or use default'
        required: false
        default: 'latest'
        type: string
  schedule:
    - cron: '30 11 * * 5'

jobs:
  docker:
    name: NP_server
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.inputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.UNCLE_ANDY_DOCKERHUB_USERNAME }}
          password: ${{ secrets.UNCLE_ANDY_DOCKERHUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set tag
        run: |
          if [ -z "$TAG" ]; then
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: ARCH=${{ env.ARCH }}
          context: .
          file: ./support/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.UNCLE_ANDY_DOCKERHUB_USERNAME }}/netpanzer:${{ env.TAG }}
